### ISSUE TITLE
circletype.min.js once work only when i reload the page

### ISSUE THREAD

**Issue by Hellobast** [peterhry/CircleType#108]
Hi, 

I used circletype.min.js in my wordpress with in header : 

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script type="text/javascript" src="http://www.lacourdesvins.fr/wp-admin/js/circletype.min.js"></script> 

and i've created Html module with visual composer with : 
![capture d ecran 2018-11-30 a 11 41 26](https://user-images.githubusercontent.com/45485272/49284627-65cc6a80-f495-11e8-8fa5-026c8d1a02ac.png)

When i load the page the tittle load bad (picture 1), but when i reload the tittle is good (picture2) ...
 
![picture-1](https://user-images.githubusercontent.com/45485272/49284508-171ed080-f495-11e8-9ccb-639eaceee352.png)
![picture-2](https://user-images.githubusercontent.com/45485272/49284509-171ed080-f495-11e8-8fdd-68d4688a0504.png)

Can you help me please ? 

Thanks,
Bastien

**Comment by peterhry** [comment]
@Hellobast Did you figure it out?

**Comment by Hellobast** [comment]
It's okay,
thanks
