### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by abdulbasit010** [peterhry/CircleType#110]
I am trying to pass plain text 'ABCD' to CircleType(). and it gives me error 
Uncaught TypeError: Cannot read property 'trim' of undefined
Actually i dont want to bind CircleType to any HTML element. i just want to pass a text to it and make it curved.

**Comment by peterhry** [comment]
That won’t work because circletype needs to measure the dimensions of each letter in order to arrange them in a circle.
