### ISSUE TITLE
DOESN'T WORK

### ISSUE THREAD

**Issue by metayerromain** [peterhry/CircleType#123]
Transform property in css doesn't work.

I have correctly followed the steps.

The JS: 
`      var curved = document.querySelectorAll('.curved-text');
        if (curved.length) {
            Array.prototype.forEach.call(curved, function (curvedItem) {
                console.log(curvedItem)
                new CircleType(curvedItem).dir(-1).radius(54);
            })
        }`

In my console of each split Letter: 

`
    position: absolute;
    bottom: 0px;
    left: 50%;
    transform: translateX(0em) rotate(0deg);
    transform-origin: center -2.35714em;
`

My job actually stop because of your work.

**Comment by peterhry** [comment]
@metayerromain Have a look at the demo page. The script clearly works. If you think this is a bug, provide a reduced test case in codepen or open a PR to fix it. 

Side note: Your attitude is disgraceful. This code is available to you for free. Have some respect.
