### ISSUE TITLE
Having trouble figuring out how to get the curved text to be spaced closer together

### ISSUE THREAD

**Issue by MannanK** [peterhry/CircleType#131]
Hey! First off just wanna say awesome job on a really helpful library, thanks!

I was having trouble getting my text to be spaced closer together. I thought it would be simply by playing around with `forceWidth` and/or `forceHeight` (still not quite sure how these work), but nothing seems to be working. Here's the text I have right now:

![Screen Shot 2020-08-10 at 7 50 21 PM](https://user-images.githubusercontent.com/9904709/89842126-bf2ddd80-db42-11ea-9edf-e731287a27a9.png)

My goal is to get the letters to be spaced closer together so that the text curves up to only around the red lines pictured below. Is there any way to achieve this through the library and/or CSS?

![Screen Shot 2020-08-10 at 7 53 53 PM](https://user-images.githubusercontent.com/9904709/89842349-5e52d500-db43-11ea-8d55-39e7ee3c1346.png)

Edit: I did decrease the font-size a bit and it helped a little, but the letters are still spaced out a little more than I'd like. It's so close!

![Screen Shot 2020-08-10 at 8 18 39 PM](https://user-images.githubusercontent.com/9904709/89843439-b5a67480-db46-11ea-9648-0311f257c0d9.png)

Thanks!

**Comment by peterhry** [comment]
Hey, glad you like the library. Did you try adjusting the CSS `letter-spacing` property?

**Comment by MannanK** [comment]
I could have sworn I tried that already, but perhaps because I was trying in the Chrome Dev Tools inspector directly the results were coming out wrong since the property was applied post-render, but yes that did that trick! Thanks haha.
