### ISSUE TITLE
<br> tag dosn't work when i use CircleType.

### ISSUE THREAD

**Issue by sinafapo** [peterhry/CircleType#133]
br tag dosn't work when i use CircleType.

`       <h1>welcome <br> to restaurant </h1>`
`       new CircleType(document.getElementsByTagName('H1')[0])
.dir(-1)
.radius(884);`

**Comment by danny-pearson** [comment]
You've probably sorted this by now, but I'll leave this here for anyone else who ends up here with the same issue.

CircleType uses [HTMLElement.innerText](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText) to grab only the rendered text contained in the element (no html), wraps those characters in span tags and spits them back out in a certain shape. All it sees is `welcome to restaurant` so if you wanted to do it to two lines of text, you would need two circles/arcs something along the lines of this...

```html
<h1>
  <span class="top">welcome</span>
  <span class="bottom">to restaurant</span>
</h1>
```

```js
new CircleType(document.querySelector('.top')).dir(-1).radius(884);
new CircleType(document.querySelector('.bottom')).dir(-1).radius(884);
```
