### ISSUE TITLE
Could not find a declaration file for module 'circletype'

### ISSUE THREAD

**Issue by patrickbussmann** [peterhry/CircleType#138]
In README.md you wrote:

    import CircleType from `circletype`;

But there are no types for this module.

    error TS7016: Could not find a declaration file for module 'circletype'
    Try `npm install @types/circletype` if it exists or add a new declaration (.d.ts) file containing `declare module 'circletype';`

So its not as easy as install & use.

**Comment by peterhry** [comment]
This is a JavaScript library. I’m not sure what’s needed to make it work with TypeScript. Good luck.

**Comment by thingsneverchange** [comment]
This may be helpful.
```
declare module 'circletype' {
    export interface CircleTypeOptions {
        radius?: number;
        dir?: number;
        forceWidth?: boolean;
        forceHeight?: boolean;
    }

    export default class CircleType {
        constructor(element: HTMLElement, options?: CircleTypeOptions);
        radius(radius: number): this;
        dir(dir: number): this;
        forceWidth(force: boolean): this;
        forceHeight(force: boolean): this;
        refresh(): void;
        destroy(): void;
    }
}
```
