### ISSUE TITLE
Destroy effect

### ISSUE THREAD

**Issue by ghost** [peterhry/CircleType#14]
Hi Peter,

Your plugin is very interesting and work perfectly, but i have one problem : I need to remove dynamically the effect, and you didn't add such method in your plugin to make that. Could you explain me how to create this function easily ?

Thanks in advance

**Comment by jkbyln** [comment]
I second this!

**Comment by peterhry** [comment]
working on this now

**Comment by peterhry** [comment]
Added in 2.0
