### ISSUE TITLE
angular2 compatible?

### ISSUE THREAD

**Issue by estradamarkie** [peterhry/CircleType#19]
Does it work on ng2 by any chance? or any plans of making one for ng2?

**Comment by peterhry** [comment]
jQuery plugins like this don’t typically work well in frameworks like Angular, React, etc. I’m sure there’s a way to make it work in Angular but I doubt it would be elegant. 

I don’t have any specific plan for ng2 but I do plan to refactor circletype into a vanilla JS library at some point. Hopefully that will make it more interoperable with current frameworks.
