### ISSUE TITLE
Semicolon error in npm installed with yarn

### ISSUE THREAD

**Issue by hisie** [peterhry/CircleType#20]
I have installed a version with bower and it is working. However, I have installed circleType with yarn in another project and, when i do gulp to generate the app.js file, the file generated does not work. The error is:
`TypeError: (intermediate value)(...) is not a function`
When i go to the file /node_modules/circletype.js/circletype.js i can see these last lines:

`
      if (document.readyState !== 'complete') {
        elem.style.visibility = 'hidden'
        $(window).on('load', function () {
          elem.style.visibility = 'visible'
          layout()
        })
      } else {
        layout()
      }
    })
  }
}))
`
If I manually add a semicolon at the end of the last line and i do the gulp process it works like a charm. In the bower version the file finish fine with semicolon.

I have resolved the problem by placing circletype library at the last position of the gulpfile. This way there are no more libraries after circleType and there is no error. But I don't think this is a definitive solution.

**Comment by peterhry** [comment]
Are you using this fork?
https://github.com/mike3run/CircleType/blob/master/circletype.js
It looks like the semicolons were removed from this version, for some reason.

**Comment by peterhry** [comment]
I will add package.json so you can load this npm.

**Comment by peterhry** [comment]
@hisie You can now install this package with npm:
`npm i circletype --save`
