### ISSUE TITLE
Incompatible with IE 11 (Array.from)

### ISSUE THREAD

**Issue by shabla** [peterhry/CircleType#89]
Doesn't work on IE 11 because it doesn't have Array.from, it seems to be the only things preventing use on IE.

For anyone having this problem, I used the polyfill available on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) and it works as expected.

**Comment by peterhry** [comment]
Thanks @shabla !
